// lib/exporter/next/nextExporter.ts

import { BuilderSchema, BuilderPage } from "@/lib/exporter/schema"
import { generateNextPage } from "./pageGenerator"

/* ============================================================
   TYPES
============================================================ */

export type GeneratedFile = {
  path: string
  content: string
}

export type ExportResult = {
  files: GeneratedFile[]
}

/* ============================================================
   MAIN EXPORTER
============================================================ */

export function exportNextApp(schema: BuilderSchema): ExportResult {
  const files: GeneratedFile[] = []

  /* =============================
     1. Root Layout
  ============================== */

  files.push({
    path: "app/layout.tsx",
    content: generateRootLayout(),
  })

  /* =============================
     2. Pages
  ============================== */

  schema.pages.forEach((page) => {
    const filePath = resolvePagePath(page)
    const pageContent = generateNextPage(page)

    files.push({
      path: filePath,
      content: pageContent,
    })
  })

  return { files }
}

/* ============================================================
   ROUTE RESOLUTION
============================================================ */

function resolvePagePath(page: BuilderPage): string {
  if (page.route === "/" || page.route === "") {
    return "app/page.tsx"
  }

  // Remove leading slash
  const cleaned = page.route.replace(/^\//, "")

  return `app/${cleaned}/page.tsx`
}

/* ============================================================
   ROOT LAYOUT
============================================================ */

function generateRootLayout(): string {
  return `
export const metadata = {
  title: "AI App Builder Export",
  description: "Generated by AI App Builder",
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body style={{ margin: 0, fontFamily: "sans-serif" }}>
        {children}
      </body>
    </html>
  )
}
`.trim()
}
