//
//  generateComponent.ts
//  AI-App-Builder-Pro
//
//  Created by Squally Da Boss on 2/14/26.
//


import { BuilderComponent } from "@/app/builder/state/builderStore"
import { mapPropsToTailwind } from "./tailwindMapper"

export function generateComponentTree(components: BuilderComponent[]): string {
  return components
    .map((comp) => {
      const classes = mapPropsToTailwind(comp.props)
      const children = comp.children ? generateComponentTree(comp.children) : ""
      return `<div id="${comp.id}" className="${classes}">${children}</div>`
    })
    .join("\n")
}

export function generateComponentTree(
  components: BuilderComponent[]
): string {
  return components
    .map((component) => generateComponent(component))
    .join("\n")
}
function generatePackageJson() {
  return JSON.stringify(
    {
      name: "ai-builder-export",
      private: true,
      scripts: {
        dev: "next dev",
        build: "next build",
        start: "next start"
      },
      dependencies: {
        next: "latest",
        react: "latest",
        "react-dom": "latest"
      }
    },
    null,
    2
  )
}

function generateTsConfig() {
  return JSON.stringify(
    {
      compilerOptions: {
        target: "esnext",
        module: "esnext",
        jsx: "preserve",
        strict: true
      }
    },
    null,
    2
  )
}

function generateRootLayout() {
  return `
import "./globals.css"

export const metadata = {
  title: "AI Builder App",
  description: "Generated by AI App Builder Pro"
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>{children}</body>
    </html>
  )
}
`
}

function generateGlobalCss() {
  return `
@tailwind base;
@tailwind components;
@tailwind utilities;

html, body {
  height: 100%;
}
`
}

function generateComponent(component: BuilderComponent): string {
  switch (component.type) {
    case "text":
      return `<p>${component.props?.text || "Text"}</p>`

    case "button":
      return `<button className="px-4 py-2 bg-black text-white rounded">
        ${component.props?.label || "Button"}
      </button>`

    case "container":
      return `
<div className="p-4 border">
  ${generateComponentTree(component.children || [])}
</div>
      `

    default:
      return `<div>Unknown Component</div>`
  }
}
